CREATE SCHEMA `MEFIT`;

CREATE TABLE `MEFIT`.`WORKOUT_PLAN` (
                                              `ID` int PRIMARY KEY AUTO_INCREMENT,
                                              `CREATE_DATE` date default CURRENT_TIMESTAMP,
                                              `USER_ID` int NOT NULL,
                                              `PERSONAL_ID` int NOT NULL,
                                              `REPS` int NOT NULL,
                                              `SERIES` int NOT NULL,
                                              `START_DATE` date NOT NULL,
                                              `END_DATE` date NOT NULL,
                                              `ACTIVE` boolean default true,
                                              `SENT` boolean default false
);

CREATE TABLE `MEFIT`.`WORKOUT_DAY` (
                                          `ID` int PRIMARY KEY AUTO_INCREMENT,
                                          `CREATE_DATE` date default CURRENT_TIMESTAMP,
                                          `WEEK_DAY` varchar(255) NOT NULL,
                                          `WORKOUT_PLAN_ID` int
);

CREATE TABLE `MEFIT`.`EXERCISE` (
                                       `ID` int PRIMARY KEY AUTO_INCREMENT,
                                       `CREATE_DATE` date default CURRENT_TIMESTAMP,
                                       `NAME` varchar(255) NOT NULL,
                                       `MUSCULAR_GROUP` ENUM ('PEITO', 'OMBRO', 'PERNA', 'PANTURRILHA', 'COSTAS', 'BICEPS', 'TRICEPS') NOT NULL,
                                       `ACTIVE` boolean  default true
);

CREATE TABLE `MEFIT`.`WORKOUT_DAY_X_EXERCISE` (
                                                     `EXERCISE_ID` int NOT NULL,
                                                     `WORKOUT_DAY_ID` int NOT NULL,
                                                     PRIMARY KEY (`WORKOUT_DAY_ID`, `EXERCISE_ID`)
);

CREATE TABLE `MEFIT`.`USER_TYPE`
(
    id   INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255)
);

CREATE TABLE `MEFIT`.`MEFIT_USER`
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login        VARCHAR(255),
    name         VARCHAR(255),
    passwd       VARCHAR(255),
    status       VARCHAR(255)                            NOT NULL,
    user_type_id BIGINT
);

ALTER TABLE `MEFIT`.`EXERCISE` ADD CONSTRAINT `UC_Exercise_name` UNIQUE (NAME);

ALTER TABLE `MEFIT`.`MEFIT_USER`
    ADD CONSTRAINT FK_USER_ON_USER_TYPE FOREIGN KEY (user_type_id) REFERENCES `MEFIT`.`USER_TYPE` (id);

ALTER TABLE `MEFIT`.`WORKOUT_DAY` ADD FOREIGN KEY (`WORKOUT_PLAN_ID`) REFERENCES `MEFIT`.`WORKOUT_PLAN` (`ID`);

ALTER TABLE `MEFIT`.`WORKOUT_DAY_X_EXERCISE` ADD FOREIGN KEY (`WORKOUT_DAY_ID`) REFERENCES `MEFIT`.`WORKOUT_DAY` (`ID`);

ALTER TABLE `MEFIT`.`WORKOUT_DAY_X_EXERCISE` ADD FOREIGN KEY (`EXERCISE_ID`) REFERENCES `MEFIT`.`EXERCISE` (`ID`);

ALTER TABLE `MEFIT`.`WORKOUT_PLAN`
    ADD CONSTRAINT FK_WORKOUT_PLAN_ON_USER_TYPE FOREIGN KEY (USER_ID) REFERENCES `MEFIT`.`USER_TYPE` (id);

ALTER TABLE `MEFIT`.`WORKOUT_PLAN`
    ADD CONSTRAINT FK_WORKOUT_PLAN_ON_PERSONAL_TRAINER FOREIGN KEY (PERSONAL_ID) REFERENCES `MEFIT`.`USER_TYPE` (id);
