
-- PEITO

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Crossover inferior', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Crossover reto', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Crucifixo inclinado', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Crucifixo reto', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Supino frontal', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Supino inclinado', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Supino maquina', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Supino reto com halter', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Supino reto', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Voador', 'PEITO', CURRENT_TIMESTAMP(), 'TRUE');

-- OMBRO

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Desenvolvimento articulado', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Desenvolvimento barra frente', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Desenvolvimento halter', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Elevação frontal barra', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Elevação frontal crossover', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Elevação lateral sentado', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Elevação lateral', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Elevação unilateral crossover', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Encolhimento barra costas', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Encolhimento barra frente', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Encolhimento halter', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Remada alta', 'OMBRO', CURRENT_TIMESTAMP(), 'TRUE');

-- PERNA

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Adutores', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Agachamento afundo', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Agachamento livre', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Extensora', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Flexora', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Leg press', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Passada', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Perna', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Stiff', 'PERNA', CURRENT_TIMESTAMP(), 'TRUE');

-- PANTURRILHA

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Panturrilha livre', 'PANTURRILHA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Panturrilha máquina', 'PANTURRILHA', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Panturrilha sentada', 'PANTURRILHA', CURRENT_TIMESTAMP(), 'TRUE');

-- COSTAS

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Cavalo aberto', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Crucifixo invertido', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Puxada frente aberta', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Puxada frente fechada', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Remada sentada aberta pegada pronada', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Remada sentada aberta', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Remada sentada fechada', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Remada unilateral', 'COSTAS', CURRENT_TIMESTAMP(), 'TRUE');


-- BICEPS

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca 21', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca alternada', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca crossover', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca direta crossover', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca direta', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca invertida', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca martelo com giro', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca punho', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Rosca scott barra W (pegada fechada)', 'BICEPS', CURRENT_TIMESTAMP(), 'TRUE');

-- TRICEPS

INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps barra reta invertida', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps barra V', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps coice', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps corda unilateral', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps corda', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps francês', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');
INSERT INTO WORKOUTS.EXERCISE (NAME, MUSCULAR_GROUP, CREATE_DATE, ACTIVE) VALUES ('Tríceps testa', 'TRICEPS', CURRENT_TIMESTAMP(), 'TRUE');



