create table TREINAMENTOS.DIA_TREINAMENTO_X_EXERCICIO
(
    EXERCICIO_ID       INTEGER not null
        references TREINAMENTOS.EXERCICIO,
    DIA_TREINAMENTO_ID INTEGER not null
        references TREINAMENTOS.DIA_TREINAMENTO,
    primary key (DIA_TREINAMENTO_ID, EXERCICIO_ID)
);

