# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - mefit-gateway

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/mefit-gateway/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build mefit-gateway service
        run: cd ${{ github.workspace }}/back-end/mefit-gateway  && chmod +x gradlew && ./gradlew clean build

      - name: Upload mefit-gateway artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: mefit-gateway
          path: '${{ github.workspace }}/back-end/mefit-gateway/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: mefit-gateway

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mefit-gateway'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8607535955D34BB6B9329566D2F0AEDE }}
          package: '*SNAPSHOT.jar'
