# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - me-fit-workout-plan-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build plano-treinamento
        run: cd ${{ github.workspace }}/back-end/plano-treinamento  && chmod +x gradlew && ./gradlew clean build

      - name: Upload plano-treinamento artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: plano-treinamento
          path: '${{ github.workspace }}/back-end/plano-treinamento/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: plano-treinamento

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'me-fit-workout-plan-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E8E66147DC1043D29219282F92B18722 }}
          package: '*SNAPSHOT.jar'
