name: Registry service - Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/service-registration-and-discovery/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build service-registration-service
        run: cd ${{ github.workspace }}/back-end/service-registration-and-discovery && chmod +x gradlew && ./gradlew clean build

      - name: Upload service-registration-and-discovery artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: service-registration-and-discovery
          path: '${{ github.workspace }}/back-end/service-registration-and-discovery/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: service-registration-and-discovery

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'registry-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9845557D9A96403B9D5A945D5A64F7D5 }}
          package: '*SNAPSHOT.jar'

